name: Docker Build and Publish

on:
  workflow_dispatch:


jobs:
  release-docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history for proper versioning

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Extract version
        id: version
        run: |
          # Default to 'dev' for non-tag builds
          VERSION=dev
          
          # If this is a tag, use the tag name without the 'v' prefix
          if [[ $GITHUB_REF == refs/tags/v* ]]; then
            VERSION=${GITHUB_REF#refs/tags/v}
          fi
          
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
          echo "Building version: $VERSION"

      - name: Log in to GitHub Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ghcr.io/${{ github.repository }}:latest
            ${{ github.ref_type == 'tag' && format('ghcr.io/{0}:{1}', github.repository, steps.version.outputs.VERSION) || '' }}
          build-args: |
            VERSION=${{ steps.version.outputs.VERSION }}
          labels: |
            org.opencontainers.image.created=${{ github.event.repository.updated_at }}
            org.opencontainers.image.version=${{ steps.version.outputs.VERSION }}
            org.opencontainers.image.revision=${{ github.sha }}

  release-helm:
    permissions:
      contents: write

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
        # fetch-tags: true - from experience, this usually results in errors
        # > Also see: https://github.com/actions/checkout/issues/1467

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Package and upload helm chart
        run: |
          # download helm chart releaser
          curl -sSLo cr.tar.gz "https://github.com/helm/chart-releaser/releases/download/v1.6.0/chart-releaser_1.6.0_linux_amd64.tar.gz"
          tar -xzf cr.tar.gz
          rm -f cr.tar.gz
          owner=$(cut -d '/' -f 1 <<< "$GITHUB_REPOSITORY")
          repo=$(cut -d '/' -f 2 <<< "$GITHUB_REPOSITORY")
          # package chart
          ./cr package charts/$repo
          # upload chart to github releases
          ./cr upload \
              --owner "$owner" \
              --git-repo "$repo" \
              --token "${{ secrets.GITHUB_TOKEN }}" \
              --release-name-template "{{ .Version }}"
          # update index and push to github pages
          git config user.email "$owner@users.noreply.github.com"
          git config user.name "$owner"
          ./cr index \
              --owner "$owner" \
              --git-repo "$repo" \
              --token "${{ secrets.GITHUB_TOKEN }}" \
              --release-name-template "{{ .Version }}" \
              --index-path ./index.yaml \
              --charts-repo https://$owner.github.io/$repo \
              --push

      - name: Add commit digest to GH release
        run: |
          git fetch --tags
          LAST_TAG=$(git tag --list 'v*' --sort=-v:refname | sed -n '2p')
          CURRENT_TAG=$(git tag --list 'v*' --sort=-v:refname | sed -n '1p')
          COMMITS=$(git log --oneline ${LAST_TAG}..${CURRENT_TAG} | sed 's/^/- /')
          
          # Workaround to get newlines working
          echo -e "### Changes since \`${LAST_TAG}\`\n\n${COMMITS}" > msg
          gh release edit ${CURRENT_TAG} --notes "$(cat msg)"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}